name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger the workflow for version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --icon=imgs/iCloudSync_icon.png --add-data "imgs/iCloudSync_icon.png;imgs" src/iCoudSyncImgConverter.py

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: icoudsyncimgconverter
          path: dist/iCoudSyncImgConverter.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: icoudsyncimgconverter
          path: dist

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: dist/iCoudSyncImgConverter.exe
