name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger the workflow for version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --icon=imgs/iCloudSync_icon.ico --add-data "imgs/iCloudSync_icon.png;imgs" src/iCoudSyncImgConverter.py

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: icoudsyncimgconverter
          path: dist/iCoudSyncImgConverter.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Create dist directory
        run: mkdir dist

      - name: Download build artifacts
        uses: actions/download-artifact@main
        with:
          name: icoudsyncimgconverter
          path: dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/iCoudSyncImgConverter.exe
          asset_name: iCoudSyncImgConverter.exe
          asset_content_type: application/octet-stream